### ISSUE TITLE
Can you provide any screenshot ?

### ISSUE THREAD

**Issue by issour** [anditsung/nova-custom#1]
Thx !!

**Comment by anditsung** [comment]
<img width="1050" alt="Screen Shot 2020-05-15 at 08 45 18" src="https://user-images.githubusercontent.com/1090413/82002621-6f955e00-9688-11ea-8abb-f94515d6ba44.png">

then end result is like this
there is a new resign button at the end

**Comment by issour** [comment]
Oh !! very nice 👍 
it's like à custom action but in tool bar ?

**Comment by anditsung** [comment]
not toolbar, toolbar is on the detail page
but this is on index page and on each of the resource row
